### ISSUE TITLE
Putting FPS, potion status, direction, coords, fps and ping to the right of the game frame can set them outside the screen if the number is too big

### ISSUE THREAD

**Issue by zamaga** [Lowdinggg/SaphyrMC#6]
PREVIEW http://imgur.com/a/eiTLg
REALITY http://imgur.com/a/Cij8x

**Comment by Lowdinggg** [comment]
There is a fucking button called reset position for that. Renseigne toi before; Thanks

**Comment by zamaga** [comment]
You did not "fucking" understand.
